import { IPUCollege } from '../types';

export const IPU_COLLEGES: IPUCollege[] = [
  // University Schools of Studies (USS) - Main Campus Dwarka & East Delhi
  {
    id: 'usict',
    name: 'University School of Information, Communication and Technology',
    shortName: 'USICT',
    campus: 'GGSIPU Main Campus, Sector 16-C, Dwarka, New Delhi',
    code: '164',
    isMainCampus: true,
  },
  {
    id: 'usar',
    name: 'University School of Automation and Robotics',
    shortName: 'USAR',
    campus: 'GGSIPU East Delhi Campus, Surajmal Vihar, Delhi',
    code: '190',
    isMainCampus: true,
  },
  {
    id: 'usdi',
    name: 'University School of Design and Innovation',
    shortName: 'USDI',
    campus: 'GGSIPU East Delhi Campus, Surajmal Vihar, Delhi',
    code: '191',
    isMainCampus: true,
  },
  {
    id: 'uslls',
    name: 'University School of Law and Legal Studies',
    shortName: 'USLLS',
    campus: 'GGSIPU Main Campus, Dwarka, New Delhi',
    code: '165',
    isMainCampus: true,
  },
  {
    id: 'usms',
    name: 'University School of Management Studies',
    shortName: 'USMS',
    campus: 'GGSIPU Main Campus, Dwarka, New Delhi',
    code: '166',
    isMainCampus: true,
  },
  {
    id: 'usap',
    name: 'University School of Architecture and Planning',
    shortName: 'USAP',
    campus: 'GGSIPU Main Campus, Dwarka, New Delhi',
    code: '167',
    isMainCampus: true,
  },
  {
    id: 'usbt',
    name: 'University School of Biotechnology',
    shortName: 'USBT',
    campus: 'GGSIPU Main Campus, Dwarka, New Delhi',
    code: '168',
    isMainCampus: true,
  },
  {
    id: 'usmc',
    name: 'University School of Mass Communication',
    shortName: 'USMC',
    campus: 'GGSIPU Main Campus, Dwarka, New Delhi',
    code: '169',
    isMainCampus: true,
  },

  // Top Affiliated Institutions
  {
    id: 'bpit',
    name: 'Bhagwan Parshuram Institute of Technology',
    shortName: 'BPIT',
    campus: 'PSP-4, Sector 17, Rohini, Delhi',
    code: '208',
  },
  {
    id: 'mait',
    name: 'Maharaja Agrasen Institute of Technology',
    shortName: 'MAIT',
    campus: 'PSP Area, Sector 22, Rohini, Delhi',
    code: '148',
  },
  {
    id: 'msit',
    name: 'Maharaja Surajmal Institute of Technology',
    shortName: 'MSIT',
    campus: 'C-4, Janakpuri, New Delhi',
    code: '963',
  },
  {
    id: 'msi',
    name: 'Maharaja Surajmal Institute',
    shortName: 'MSI',
    campus: 'C-4, Janakpuri, New Delhi',
    code: '149',
  },
  {
    id: 'bvcoe',
    name: "Bharati Vidyapeeth's College of Engineering",
    shortName: 'BVCOE',
    campus: 'A-4, Paschim Vihar, New Delhi',
    code: '115',
  },
  {
    id: 'vips',
    name: 'Vivekananda Institute of Professional Studies',
    shortName: 'VIPS',
    campus: 'AU Block, Outer Ring Road, Pitampura, Delhi',
    code: '177',
  },
  {
    id: 'adgitm',
    name: 'Dr. Akhilesh Das Gupta Institute of Technology & Management (formerly NIEC)',
    shortName: 'ADGITM',
    campus: 'FC-26, Shastri Park, New Delhi',
    code: '156',
  },
  {
    id: 'gtbit',
    name: 'Guru Tegh Bahadur Institute of Technology',
    shortName: 'GTBIT',
    campus: 'G-8 Area, Rajouri Garden, New Delhi',
    code: '132',
  },
  {
    id: 'jims-rohini',
    name: 'Jagan Institute of Management Studies (Rohini)',
    shortName: 'JIMS Rohini',
    campus: '3, Institutional Area, Sector 5, Rohini, Delhi',
    code: '140',
  },
  {
    id: 'jims-kalkaji',
    name: 'Jagannath International Management School (Kalkaji)',
    shortName: 'JIMS Kalkaji',
    campus: 'Morpeth House, Kalkaji, New Delhi',
    code: '141',
  },
  {
    id: 'jims-vk',
    name: 'Jagannath International Management School (Vasant Kunj)',
    shortName: 'JIMS Vasant Kunj',
    campus: 'OCF Pocket 9, Sector B, Vasant Kunj, New Delhi',
    code: '142',
  },
  {
    id: 'tips',
    name: 'Trinity Institute of Professional Studies',
    shortName: 'TIPS',
    campus: 'Sector 9, Dwarka, New Delhi',
    code: '206',
  },
  {
    id: 'dtc',
    name: 'Delhi Technical Campus',
    shortName: 'DTC',
    campus: 'Knowledge Park III, Greater Noida, UP',
    code: '180',
  },
  {
    id: 'gibs',
    name: 'Gitarattan International Business School',
    shortName: 'GIBS',
    campus: 'PSP 2A & 2B, Madhuban Chowk, Rohini, Delhi',
    code: '193',
  },
  {
    id: 'fimt',
    name: 'Fairfield Institute of Management and Technology',
    shortName: 'FIMT',
    campus: 'FIMT Campus, Kapashera, New Delhi',
    code: '901',
  },
  {
    id: 'hmritm',
    name: 'HMR Institute of Technology & Management',
    shortName: 'HMRITM',
    campus: 'Plot No. 326, Hamidpur, Delhi',
    code: '133',
  },
  {
    id: 'meri',
    name: 'Management Education & Research Institute',
    shortName: 'MERI',
    campus: '53-54, Institutional Area, Janakpuri, New Delhi',
    code: '151',
  },
  {
    id: 'tias',
    name: 'Tecnia Institute of Advanced Studies',
    shortName: 'TIAS',
    campus: '3 PSP, Institutional Area, Madhuban Chowk, Rohini, Delhi',
    code: '170',
  },
  {
    id: 'cpj',
    name: 'Chanderprabhu Jain College of Higher Studies & School of Law',
    shortName: 'CPJ College',
    campus: 'Plot No. OCF, Sector A-8, Narela, Delhi',
    code: '215',
  },
  {
    id: 'iimt',
    name: 'Ideal Institute of Management and Technology',
    shortName: 'IIMT',
    campus: '16 X, Karkardooma Institutional Area, Delhi',
    code: '134',
  },
];

export const IPU_PROGRAMMES = [
  'B.Tech',
  'BCA',
  'BBA',
  'BA LLB',
  'BBA LLB',
  'MBA',
  'MCA',
  'B.Com (Hons)',
  'B.Pharm',
  'BJMC / BA(JMC)',
  'B.Ed',
  'M.Tech',
  'LLM',
];

export const IPU_BTECH_BRANCHES = [
  'CSE (Computer Science & Engineering)',
  'IT (Information Technology)',
  'ECE (Electronics & Communication)',
  'AI & ML (Artificial Intelligence & Machine Learning)',
  'AI & DS (Artificial Intelligence & Data Science)',
  'CSE (AI)',
  'CSE (DS)',
  'CSE (Cyber Security)',
  'CSE (IoT)',
  'EEE (Electrical & Electronics)',
  'Mechanical & Automation',
  'Civil Engineering',
  'Robotics & Automation',
  'IIoT (Industrial IoT)',
];

export const IPU_GENERIC_BRANCHES: Record<string, string[]> = {
  'BCA': ['Standard BCA', 'BCA (Data Science)', 'BCA (Cloud Computing)'],
  'BBA': ['General BBA', 'BBA (Banking & Insurance)', 'BBA (Financial Analysis)', 'BBA (Digital Marketing)'],
  'BA LLB': ['Five Year Integrated Law'],
  'BBA LLB': ['Five Year Integrated Law (BBA)'],
  'MBA': ['MBA (General)', 'MBA (Financial Markets)', 'MBA (International Business)', 'MBA (Analytics)'],
  'MCA': ['MCA (Standard)', 'MCA (Software Engineering)'],
  'B.Com (Hons)': ['Standard'],
  'BJMC / BA(JMC)': ['Journalism & Mass Comm'],
};
