import {
  StudentProfile,
  Subject,
  TimetableSlot,
  AttendanceRecord,
  AcademicExam,
} from '../types';

export const SAMPLE_IPU_PROFILE: StudentProfile = {
  name: '',
  college: '',
  collegeShort: '',
  programme: 'B.Tech',
  branch: '',
  semester: 1,
  section: '',
  academicSession: '2026–27',
  targetAttendance: 75,
  isIPUMode: true,
  isOnboarded: false,
};

export const SAMPLE_IPU_SUBJECTS: Subject[] = [
  {
    id: 'sub_dsa',
    name: 'Data Structures & Algorithms',
    code: 'CIC-201',
    type: 'Theory',
    credits: 4,
    ltp: '3-1-0',
    faculty: 'Dr. Amit Sharma',
    room: 'A-204',
    targetRequirement: 75,
    attended: 24,
    total: 28,
    cancelled: 1,
    od: 0,
    color: '#6366F1',
    isLab2x: false,
  },
  {
    id: 'sub_os',
    name: 'Operating Systems',
    code: 'CIC-203',
    type: 'Theory',
    credits: 4,
    ltp: '3-1-0',
    faculty: 'Prof. Neha Gupta',
    room: 'B-102',
    targetRequirement: 75,
    attended: 21,
    total: 28,
    cancelled: 2,
    od: 0,
    color: '#10B981',
    isLab2x: false,
  },
  {
    id: 'sub_dbms',
    name: 'Database Management Systems',
    code: 'CIC-205',
    type: 'Theory',
    credits: 4,
    ltp: '3-0-0',
    faculty: 'Dr. Rajesh Verma',
    room: 'C-301',
    targetRequirement: 75,
    attended: 18,
    total: 26,
    cancelled: 0,
    od: 1,
    color: '#F43F5E',
    isLab2x: false,
  },
  {
    id: 'sub_cn',
    name: 'Computer Networks',
    code: 'CIC-207',
    type: 'Theory',
    credits: 4,
    ltp: '3-1-0',
    faculty: 'Dr. Priya Malik',
    room: 'A-204',
    targetRequirement: 75,
    attended: 26,
    total: 28,
    cancelled: 1,
    od: 0,
    color: '#38BDF8',
    isLab2x: false,
  },
  {
    id: 'sub_dsa_lab',
    name: 'DSA & OS Laboratory',
    code: 'CIC-251',
    type: 'Lab',
    credits: 2,
    ltp: '0-0-4',
    faculty: 'Dr. Amit Sharma',
    room: 'Lab-4',
    targetRequirement: 75,
    attended: 10,
    total: 12,
    cancelled: 0,
    od: 0,
    color: '#F59E0B',
    isLab2x: true,
  },
];

export const SAMPLE_IPU_TIMETABLE: TimetableSlot[] = [
  // Monday
  {
    id: 'tt_mon_1',
    day: 'MON',
    startTime: '09:30',
    endTime: '10:30',
    subjectId: 'sub_dsa',
    subjectName: 'Data Structures & Algorithms',
    subjectCode: 'CIC-201',
    type: 'Theory',
    room: 'A-204',
    faculty: 'Dr. Amit Sharma',
  },
  {
    id: 'tt_mon_2',
    day: 'MON',
    startTime: '10:30',
    endTime: '11:30',
    subjectId: 'sub_os',
    subjectName: 'Operating Systems',
    subjectCode: 'CIC-203',
    type: 'Theory',
    room: 'B-102',
    faculty: 'Prof. Neha Gupta',
  },
  {
    id: 'tt_mon_3',
    day: 'MON',
    startTime: '11:30',
    endTime: '12:30',
    subjectId: 'sub_cn',
    subjectName: 'Computer Networks',
    subjectCode: 'CIC-207',
    type: 'Theory',
    room: 'A-204',
    faculty: 'Dr. Priya Malik',
  },
  // Tuesday
  {
    id: 'tt_tue_1',
    day: 'TUE',
    startTime: '09:30',
    endTime: '10:30',
    subjectId: 'sub_dbms',
    subjectName: 'Database Management Systems',
    subjectCode: 'CIC-205',
    type: 'Theory',
    room: 'C-301',
    faculty: 'Dr. Rajesh Verma',
  },
  {
    id: 'tt_tue_2',
    day: 'TUE',
    startTime: '11:30',
    endTime: '12:30',
    subjectId: 'sub_os',
    subjectName: 'Operating Systems',
    subjectCode: 'CIC-203',
    type: 'Theory',
    room: 'B-102',
    faculty: 'Prof. Neha Gupta',
  },
  {
    id: 'tt_tue_3',
    day: 'TUE',
    startTime: '01:30',
    endTime: '03:30',
    subjectId: 'sub_dsa_lab',
    subjectName: 'DSA & OS Laboratory',
    subjectCode: 'CIC-251',
    type: 'Lab',
    room: 'Lab-4',
    faculty: 'Dr. Amit Sharma',
  },
  // Wednesday
  {
    id: 'tt_wed_1',
    day: 'WED',
    startTime: '09:30',
    endTime: '10:30',
    subjectId: 'sub_cn',
    subjectName: 'Computer Networks',
    subjectCode: 'CIC-207',
    type: 'Theory',
    room: 'A-204',
    faculty: 'Dr. Priya Malik',
  },
  {
    id: 'tt_wed_2',
    day: 'WED',
    startTime: '10:30',
    endTime: '11:30',
    subjectId: 'sub_dsa',
    subjectName: 'Data Structures & Algorithms',
    subjectCode: 'CIC-201',
    type: 'Theory',
    room: 'A-204',
    faculty: 'Dr. Amit Sharma',
  },
  // Thursday
  {
    id: 'tt_thu_1',
    day: 'THU',
    startTime: '09:30',
    endTime: '10:30',
    subjectId: 'sub_os',
    subjectName: 'Operating Systems',
    subjectCode: 'CIC-203',
    type: 'Theory',
    room: 'B-102',
    faculty: 'Prof. Neha Gupta',
  },
  {
    id: 'tt_thu_2',
    day: 'THU',
    startTime: '10:30',
    endTime: '11:30',
    subjectId: 'sub_dbms',
    subjectName: 'Database Management Systems',
    subjectCode: 'CIC-205',
    type: 'Theory',
    room: 'C-301',
    faculty: 'Dr. Rajesh Verma',
  },
  // Friday
  {
    id: 'tt_fri_1',
    day: 'FRI',
    startTime: '10:30',
    endTime: '11:30',
    subjectId: 'sub_cn',
    subjectName: 'Computer Networks',
    subjectCode: 'CIC-207',
    type: 'Theory',
    room: 'A-204',
    faculty: 'Dr. Priya Malik',
  },
  {
    id: 'tt_fri_2',
    day: 'FRI',
    startTime: '11:30',
    endTime: '12:30',
    subjectId: 'sub_dbms',
    subjectName: 'Database Management Systems',
    subjectCode: 'CIC-205',
    type: 'Theory',
    room: 'C-301',
    faculty: 'Dr. Rajesh Verma',
  },
  {
    id: 'tt_fri_3',
    day: 'FRI',
    startTime: '01:30',
    endTime: '02:30',
    subjectId: 'sub_dsa',
    subjectName: 'Data Structures & Algorithms',
    subjectCode: 'CIC-201',
    type: 'Theory',
    room: 'A-204',
    faculty: 'Dr. Amit Sharma',
  },
];

export const SAMPLE_IPU_EXAMS: AcademicExam[] = [
  {
    id: 'exam_midsem',
    name: 'Mid-Term Examinations',
    type: 'Mid-Sem',
    date: new Date(Date.now() + 24 * 86400000).toISOString().split('T')[0],
  },
  {
    id: 'exam_endsem',
    name: 'End-Term Theory Exams',
    type: 'End-Sem',
    date: new Date(Date.now() + 68 * 86400000).toISOString().split('T')[0],
  },
];

export const SAMPLE_IPU_RECORDS: AttendanceRecord[] = [];
